#ifndef __LIMIT_H
#define __LIMIT_H

#define _BSD_SOURCE
#define _GNU_SOURCE

#include <sys/time.h>
#include <sys/resource.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdbool.h>

#define LIM_NOLIMIT	-1

struct limit {
	long memory_limit; /* in bytes, -1 for no memory limit */
	/* cpu limit is set for cpu time, while time limit is set for wall clock time. */
	long cpu_limit; /* in miliseconds, -1 for no cpu limit */
	long time_limit; /* in miliseconds, -1 for no time limit */
	long fd_limit; /* max open files allowed for the process */
	long fs_limit; /* max file size generated by the process */
	uid_t user; /* user to run the program, 0 means unchanged */
	gid_t group; /* group to run the program, 0 means unchanged */
	char *chroot; /* NULL for no chroot jail */
	char *stdin_file; /* if you need to redirect stdin to some file */
	char *stdout_file; /* if you need to redirect stdout to some file */
	bool close_fd; /* close unused fd */
	bool use_seccomp; /* use seccomp syscall filter if true */
};

int apply_limit(struct limit *);

#endif /* ifndef __LIMIT_H */
